AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ses-emailer

  # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  EmailerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: emailer/
      Handler: emailer.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: SQS
